### PR TITLE
Fix for deprecation warnings

### PR DESCRIPTION
**Pull request by BuZZ-dEE**
Let me know, if I have to do some more.

### CODE REVIEW

**Comment by purplespider** [comment]
Have you managed to get this package working with Atom v1?

**Comment by BuZZ-dEE** [comment]
I think, yes. Try the pull request / the branch to test it.

**Comment by purplespider** [comment]
Hmm, doesn't appear so:

1. Copy fork to packages/open-file-in
2. Run command "Open In: Toggle".

**Atom Version**: 1.0.11
**System**: Mac OS X 10.11
**Thrown From**: [open-in](https://github.com/danielbrodin/atom-open-in) package, v3.1.0


### Stack Trace

Failed to activate the open-in package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/james/.atom/packages/open-file-in/lib/open-in.coffee:10:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:836:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:226:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:09.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 open-in:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-scss-lint",
      "open-in",
      "open-in"
    ]
  },
  "open-in": {
    "applications": "Tower,CodeKit,Terminal"
  }
}
```

### Installed Packages

```coffee
# User
codekit-commands, v1.2.0
emmet, v2.3.12
linter, v1.5.1
linter-php, v1.0.3
minimap, v4.13.3
minimap-hide, v0.3.0
minimap-pigments, v0.1.6
modular-snippets, v0.2.1
pigments, v0.14.0
project-manager, v2.5.1
save-session, v0.15.7
silverstripe-bundle, v0.1.0

# Dev
No dev packages
```

**Comment by BuZZ-dEE** [comment]
open-file-in is the wrong folder. You need to put that in the folder of the atom-open-in plugin. I think the folder name is open-in. Have a look for the correct folder name if you have installed the original atom-open-in plugin. Then replace the content by content from the branch.

**Comment by danielbrodin** [comment]
Sorry for taking so long to merge this in. Saw it hen you made the PR, but didn't have time then and totally forgot about it. I have merged it now though and published a new version so it should be up and running again :)

**Comment by BuZZ-dEE** [comment]
Hello Daniel, no problem. Thank you.

**Comment by BuZZ-dEE** [comment]
Hello Daniel, no problem. Thank you.

Am 14. September 2015 10:43:36 WESZ, schrieb Daniel <notifications@github.com>:
>Sorry for taking so long to merge this in. Saw it hen you made the PR,
>but didn't have time then and totally forgot about it. I have merged it
>now though and published a new version so it should be up and running
>again :)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/danielbrodin/atom-open-in/pull/7#issuecomment-140019252

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Pull request merged**
